// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 000001_pre_go_acc_user_verify_9999.sql

package database

import (
	"context"
	"database/sql"
)

const getInfoOtp = `-- name: GetInfoOtp :one
SELECT verify_id, verify_otp, verify_key, verify_key_hash, verify_type, is_verified, is_deleted, verify_created_at, verify_updated_at
FROM ` + "`" + `pre_go_acc_user_verify_9999` + "`" + `
WHERE verify_key_hash = ?
`

func (q *Queries) GetInfoOtp(ctx context.Context, verifyKeyHash string) (PreGoAccUserVerify9999, error) {
	row := q.db.QueryRowContext(ctx, getInfoOtp, verifyKeyHash)
	var i PreGoAccUserVerify9999
	err := row.Scan(
		&i.VerifyID,
		&i.VerifyOtp,
		&i.VerifyKey,
		&i.VerifyKeyHash,
		&i.VerifyType,
		&i.IsVerified,
		&i.IsDeleted,
		&i.VerifyCreatedAt,
		&i.VerifyUpdatedAt,
	)
	return i, err
}

const getValidOtp = `-- name: GetValidOtp :one
SELECT verify_otp, verify_key, verify_key_hash, verify_id
FROM ` + "`" + `pre_go_acc_user_verify_9999` + "`" + `
WHERE verify_key_hash = ? AND is_verified = 0
`

type GetValidOtpRow struct {
	VerifyOtp     string
	VerifyKey     string
	VerifyKeyHash string
	VerifyID      int32
}

func (q *Queries) GetValidOtp(ctx context.Context, verifyKeyHash string) (GetValidOtpRow, error) {
	row := q.db.QueryRowContext(ctx, getValidOtp, verifyKeyHash)
	var i GetValidOtpRow
	err := row.Scan(
		&i.VerifyOtp,
		&i.VerifyKey,
		&i.VerifyKeyHash,
		&i.VerifyID,
	)
	return i, err
}

const insertOtpVerify = `-- name: InsertOtpVerify :execresult
INSERT INTO ` + "`" + `pre_go_acc_user_verify_9999` + "`" + ` (
    verify_otp,
    verify_key,
    verify_key_hash,
    verify_type,
    is_verified,
    is_deleted,
    verify_created_at,
    verify_updated_at
)
VALUES (?, ?, ?, ?, 0, 0, NOW(), NOW())
`

type InsertOtpVerifyParams struct {
	VerifyOtp     string
	VerifyKey     string
	VerifyKeyHash string
	VerifyType    sql.NullInt32
}

func (q *Queries) InsertOtpVerify(ctx context.Context, arg InsertOtpVerifyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertOtpVerify,
		arg.VerifyOtp,
		arg.VerifyKey,
		arg.VerifyKeyHash,
		arg.VerifyType,
	)
}

const updateUserVerificationStatus = `-- name: UpdateUserVerificationStatus :exec
UPDATE ` + "`" + `pre_go_acc_user_verify_9999` + "`" + `
SET is_verified = 1,
    verify_updated_at = NOW()
WHERE verify_key_hash = ?
`

func (q *Queries) UpdateUserVerificationStatus(ctx context.Context, verifyKeyHash string) error {
	_, err := q.db.ExecContext(ctx, updateUserVerificationStatus, verifyKeyHash)
	return err
}
