// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

// Account
type PreGoCrmUserC struct {
	// Account ID
	UsrID uint32
	// Email
	UsrEmail string
	// Phone number
	UsrPhone string
	// Username
	UsrUsername string
	// Password
	UsrPassword string
	// Creation time
	UsrCreatedAt int32
	// Update time
	UsrUpdatedAt int32
	// Creation IP
	UsrCreateIp string
	// Last login time
	UsrLastLoginAt int32
	// Last login IP
	UsrLastLoginIp string
	// Login times
	UsrLoginTimes int32
	// Status 1:enable, 0:disable, -1:deleted
	UsrStatus bool
}
