// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pre_go_crm_user_c.sql

package database

import (
	"context"
)

const getUserByEmailSqlc = `-- name: GetUserByEmailSqlc :one
SELECT ` + "`" + `usr_email` + "`" + `, ` + "`" + `usr_id` + "`" + ` FROM ` + "`" + `pre_go_crm_user_c` + "`" + ` WHERE ` + "`" + `usr_email` + "`" + ` = ? LIMIT 1
`

type GetUserByEmailSqlcRow struct {
	UsrEmail string
	UsrID    uint32
}

func (q *Queries) GetUserByEmailSqlc(ctx context.Context, email string) (GetUserByEmailSqlcRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailSqlc, email)
	var i GetUserByEmailSqlcRow
	err := row.Scan(&i.UsrEmail, &i.UsrID)
	return i, err
}

const updateUserStatusByUserIdSqlc = `-- name: UpdateUserStatusByUserIdSqlc :exec
UPDATE ` + "`" + `pre_go_crm_user_c` + "`" + ` 
SET ` + "`" + `usr_status` + "`" + ` = ?,
    ` + "`" + `usr_updated_at` + "`" + ` = ?
WHERE ` + "`" + `usr_id` + "`" + ` = ?
`

type UpdateUserStatusByUserIdSqlcParams struct {
	Status    bool
	Updatedat int32
	Userid    uint32
}

func (q *Queries) UpdateUserStatusByUserIdSqlc(ctx context.Context, arg UpdateUserStatusByUserIdSqlcParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatusByUserIdSqlc, arg.Status, arg.Updatedat, arg.Userid)
	return err
}
