services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: shopDevGo
    ports:
      - "5433:5432"
    volumes:
      - ./storage/postgres/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7.7
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "9091:80"
    depends_on:
      - postgres
  redis:
    image: redis:7.2-alpine
    container_name: redis_server
    ports:
      - "6380:6379"
    volumes:
      - ./storage/redis/redis_data:/data
    restart: always
