server:
  port: 8002
  mode: "dev"
mysql:
  host: 127.0.0.1 #mysql_container
  port: 33306 #3306
  userName: root
  password: root1234
  dbName: shopDevGo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  logLevel: debug
  fileName: "./storage/log/dev.001.log"
  maxSize: 500
  maxBackups: 3
  maxAge: 28
  compress: true
redis:
  host: 127.0.0.1 #redis_container
  port: 6331 #6379
  password: ""
  database: 0
  poolSize: 10

