server:
  port: 9000
postgres:
  host: 127.0.0.1
  port: 5433
  username: root
  password: root1234
  dbname: shopDevGo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  level: debug
  filename: ./storage/log/dev.001.log
  maxSize: 500
  maxBackups: 3
  maxAge: 30
  compress: true
redis:
  host: 127.0.0.1
  port: 6380
  password: ""
  db: 0
  poolSize: 10
